name: Bug report
description: สร้างรายงานบั๊กเพื่อช่วยเราในการปรับปรุง
title: "[Bug]: "
labels: ["bug"]
assignees:
  - kirati999
body:
  - type: markdown
    attributes:
      value: |
        ขอบคุณสำหรับการรายงานบั๊ก! โปรดกรอกข้อมูลให้ครบถ้วนเพื่อให้เราสามารถช่วยคุณได้เร็วที่สุด
  - type: input
    id: contact
    attributes:
      label: ช่องทางการติดต่อ
      description: หากเราต้องการข้อมูลเพิ่มเติม เราจะติดต่อคุณได้ทางไหน?
      placeholder: ตัวอย่างเช่น อีเมลหรือชื่อผู้ใช้ GitHub
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: เกิดอะไรขึ้น?
      description: โปรดอธิบายว่าเกิดอะไรขึ้น รวมถึงสิ่งที่คุณคาดว่าจะเกิดขึ้น
      placeholder: โปรดระบุรายละเอียดให้มากที่สุด
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: ขั้นตอนในการทำให้เกิดบั๊ก
      description: |
        กรุณาระบุขั้นตอนที่ชัดเจนเพื่อให้เราสามารถทำซ้ำปัญหาได้
        ตัวอย่างเช่น:
          1. ไปที่หน้า…
          2. คลิกที่ปุ่ม…
          3. เลื่อนไปที่…
          4. เห็นข้อผิดพลาด…
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: ภาพหน้าจอ
      description: หากมีภาพหน้าจอโปรดแนบไว้ด้วย
      placeholder: แนบภาพหน้าจอโดยลากไฟล์มาวางที่นี่
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: ระบบปฏิบัติการ
      description: ระบบปฏิบัติการที่คุณใช้งาน
      options:
        - Windows
        - macOS
        - Linux
        - อื่นๆ
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: เบราว์เซอร์ (ถ้าเกี่ยวข้อง)
      description: หากเป็นปัญหาที่เกี่ยวข้องกับเว็บ ให้ระบุเบราว์เซอร์ที่ใช้งาน
      placeholder: เช่น Chrome, Safari, Firefox ฯลฯ
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: ข้อมูลเพิ่มเติม
      description: ใส่ข้อมูลบริบทอื่นๆ ที่เกี่ยวข้องกับปัญหานี้
    validations:
      required: false