blank_issues_enabled: false
contact_links:
  - name: ขอเสนอฟีเจอร์ใหม่
    url: https://example.com/feature-request
    about: แนะนำแนวคิดใหม่สำหรับโปรเจกต์นี้
  - name: ขอความช่วยเหลือ
    url: https://example.com/support
    about: ขอรับความช่วยเหลือเกี่ยวกับโปรเจกต์นี้