name: ขอฟีเจอร์ใหม่
description: แนะนำฟีเจอร์ใหม่ให้กับโปรเจกต์นี้
title: "[ฟีเจอร์] <ใส่ชื่อฟีเจอร์ที่ต้องการ>"
labels: [feature]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        🙏 ขอบคุณที่เสนอไอเดียของคุณ! กรุณากรอกข้อมูลด้านล่างให้ครบถ้วนเพื่อช่วยให้เราพิจารณาได้ง่ายขึ้น
  - type: input
    id: feature_title
    attributes:
      label: ชื่อฟีเจอร์
      description: ชื่อโดยสังเขปของฟีเจอร์ที่คุณต้องการเสนอ
      placeholder: เช่น ระบบสวดมนต์อัตโนมัติ
    validations:
      required: true
  - type: textarea
    id: feature_description
    attributes:
      label: รายละเอียดของฟีเจอร์
      description: กรุณาอธิบายรายละเอียดของฟีเจอร์ที่คุณต้องการให้เพิ่มเข้ามา
      placeholder: |
        อธิบายว่าฟีเจอร์นี้ทำอะไร มีประโยชน์อย่างไร ทำงานอย่างไร หรือเชื่อมโยงกับส่วนไหนของระบบ
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: เหตุผลที่ควรเพิ่มฟีเจอร์นี้
      description: อธิบายว่าทำไมฟีเจอร์นี้ถึงมีความสำคัญหรือจำเป็น
      placeholder: |
        ฟีเจอร์นี้จะช่วยให้ผู้ใช้ทำอะไรได้ดีขึ้น หรือแก้ปัญหาอะไร
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: ทางเลือกอื่น ๆ ที่คุณลองแล้ว (ถ้ามี)
      description: คุณเคยพยายามวิธีอื่นมาก่อนหรือยัง? ถ้ามี กรุณาอธิบาย
      placeholder: เช่น เคยใช้ปลั๊กอินภายนอก แต่ไม่ตรงตามความต้องการ
    validations:
      required: false