name: Good first issue
description: Good for newcomers
labels: [good first issue]
body:
  - type: markdown
    attributes:
      value: |
        ขอขอบคุณที่ช่วยพัฒนาโปรเจกต์นี้! 🙏
  - type: textarea
    id: description
    attributes:
      label: คำอธิบายปัญหา
      description: กรุณาอธิบายปัญหาหรือฟีเจอร์ที่คุณต้องการเสนอ
      placeholder: อธิบายรายละเอียดที่นี่...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: ขั้นตอนที่แนะนำให้ทำ
      description: กรุณาระบุขั้นตอนในการแก้ไขปัญหานี้ (ถ้ามี)
      placeholder: 1. ...\n2. ...\n3. ...
    validations:
      required: false
  - type: input
    id: difficulty
    attributes:
      label: ระดับความยาก
      description: เช่น ง่าย, ปานกลาง, ยาก
      placeholder: ง่าย
    validations:
      required: false